# Dane połączenia (używamy standardowego portu i użytkownika systemowego)
# Jeśli Twój systemowy user to np. 'pik', to Postgres domyślnie stworzy taką bazę
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${USER}
spring.datasource.password=

# Driver i Dialekt
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate - automatyczne tworzenie tabel (tylko w dev!)
spring.jpa.hibernate.ddl-auto=update
#update/create a na serverze validate
spring.jpa.show-sql=true

# Wyłączenie H2 (jeśli miałeś wcześniej)
spring.h2.console.enabled=false


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG

app.jwt.secret=twoj_bardzo_dlugi_i_bezpieczny_klucz_ktory_ma_przynajmniej_32_znaki
app.jwt.expiration-ms=3600000
